### ISSUE TITLE
#1_Modifica la primera palabra de StaticWorldLibrary con tu inicial y apellido.

### ISSUE THREAD

**Issue by EntornosEdib** [EntornosEdib/AnagramGame#7]
Modifica también la palabra correspondiente en la lista Scrambed_Word_List
Realiza el commit y el push

**Comment by faresendong** [comment]
Primer issue completado

**Comment by acrespi7** [comment]
Primer issue completado - acrespi

**Comment by acrespi7** [comment]
-
